### ISSUE TITLE
There's no ./configuration script in the source tree

### ISSUE THREAD

**Issue by Stabledog** [joakim666/colortail#10]
I'd like to build this on Solaris... the README suggests that a standard configure/make/make-install might do the trick, but in fact there's no configure script.

**Comment by joakim666** [comment]
When I wrote this originally long before github my understanding was that one didn't put the ./configure script under source control but instead created it as part of the release building and included it in the tar.gz packages.

Now with everyone cloning the source tree directly from github the best practice might have changed?

**Comment by akrejczinger** [comment]
I think it's quite unexpected that the code cannot be built by following the steps in the readme.
The configure script is not the only file missing either.

**Comment by dmdmdm** [comment]
I just read about colortail in Linux Pro Magazine (June 2019, page  46).  But I ran into the missing ./configure issue too.  I ran `autoconf` and was told to run `autoreconf` but that got an error too.

**Comment by DeepInThought** [comment]
I did the following to install it.

- `git clone https://github.com/joakim666/colortail.git`
- `cd colortail/`
- `./autogen.sh`
- `./configure`
- `make`
- `sudo make install`
