### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by bfontaine** [joakim666/colortail#11]
Hello,
Would you mind tagging releases in the git repo? This would allow people to download a specific version straight from GitHub, because your site is currently down:

```
$ whois joakimandersson.se
(…)
state:            deactivated
domain:           joakimandersson.se
(…)
expires:          2015-04-26
transferred:      2009-03-06
deactivationdate: 2015-05-06
```
For the context, [Homebrew](http://brew.sh/) is using your website to download `colortail` but the URL doesn’t work anymore.

Thanks!

**Comment by joakim666** [comment]
Good idea! I missed that use of the old domain when I decommissioned the domain earlier this spring :(

I've retro-added the 0.3.3 tag and tar.gz here on github but I noticed that you've updated the homebrew formula to get a specific commit from master instead for now.

I'll make sure to tag future releases though.

**Comment by bfontaine** [comment]
Thank you!
