### ISSUE TITLE
Color all line

### ISSUE THREAD

**Issue by miscillo** [joakim666/colortail#15]
Hi. 
I don't know if what I want to do is something possible, something I wrote wrong or a possible new feature. I want to have all the line that contains a string (for example) 'error' painted red.

I tried various regex, without success. Is it possible?

Thanks, 
Miscillo

**Comment by derbeneviv** [comment]
does smth like 
error.*
or 
error\.\*
work?

i can't confirm 100% now, because i don't have colortail installed for now, but i did manage to do it 100%

**Comment by miscillo** [comment]
Nothing. That regex seems that they don't matches. I also try 
.*error.*
without success.

**Comment by miscillo** [comment]
Ok. I managed that. 
I don't know exactly why, but seems I added some tab or indent that colortail doesn't like. 
Thanks you.
